### ISSUE TITLE
run_LION

### ISSUE THREAD

**Issue by RN-Taka** [HAN-Siyu/LION_Supplementary#1]
Hi,

It's possible to run the function run_LION()  prediction with different numbers of ncRNA and Proteins?
or it's necessary to put the same number to calculate paired interaction ?
ex.:
list of ncRNA
ncRNA1 
ncRNA2
...
ncRNA10
list of proteins
pep1
pep2
...
pep15

thank you

**Comment by HAN-Siyu** [comment]
> Hi,
> 
> It's possible to run the function run_LION() prediction with different numbers of ncRNA and Proteins? or it's necessary to put the same number to calculate paired interaction ? ex.: list of ncRNA ncRNA1 ncRNA2 ... ncRNA10 list of proteins pep1 pep2 ... pep15
> 
> thank you

Hi @RN-Taka ! Thanks for using LION.

LION predicts the pairs in `seqRNA` and `seqPro`, which means for the lists of ncRNAs and proteins:

_ncRNA1
ncRNA2
...
ncRNA10_

and

_pep1
pep2
...
pep10_,

LION predicts the interaction of (ncRNA1, pep1), (ncRNA2, pep2) ... (ncRNA10, pep10).

If you would like to predict all possible pairs from these two lists, function `LION::formatSeq()` may help. Here's an example:
```
data_RNA <- seqinr::read.fasta("your_RNA_file.fa")
data_Pro <- seqinr::read.fasta("your_Pro_file.fa")

# This produces all possible pairs from data_RNA and data_Pro based on their names.
# You may need to adapt the code to your own needs.
possible_pairs <- expand.grid(unique(names(data_RNA)), 
                              unique(names(data_Pro)))  

new_RNA <- LION::formatSeq(possible_pairs[[1]], data_RNA)
new_Pro <- LION::formatSeq(possible_pairs[[2]], data_Pro) 
```
Then you can use `new_RNA` and `new_Pro` for prediction.

Just let me know if you have further questions.

**Comment by RN-Taka** [comment]
Thank you !!
It worked!
